name: Deploy

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-rust:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - build: linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            output-dir: linux-x86_64

#          - build: linux-x86
#            os: ubuntu-latest
#            target: i686-unknown-linux-gnu

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ matrix.target }}

      - name: Get the release version from the tag
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --verbose --release --target ${{ matrix.target }} --manifest-path rust/Cargo.toml

      - name: Create platform dir
        shell: bash
        run: |
          binary_name="opus_jni_rust"

          dirname="src/main/resources/natives/${{ matrix.output-dir }}"
          mkdir "$dirname"
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            mv "rust/target/${{ matrix.target }}/release/$binary_name.dll" "$dirname"
          else
            mv "rust/target/${{ matrix.target }}/release/lib$binary_name.so" "$dirname"
          fi

          echo "ASSET=$dirname" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.output-dir }}
          path: ${{ env.ASSET }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

  build:
    runs-on: ubuntu-latest
    needs: build-rust

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Download all artifacts
        uses: actions/upload-artifact@v3
        with:
          path: src/main/resources/natives

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: build/libs/opus-jni.jar
