name: Deploy

on:
  push:
    branches:
      - main
#    tags:
#      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-rust:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
#          - build: linux-x86
#            os: ubuntu-latest
#            target: i686-unknown-linux-gnu
#
#          - build: linux-x86_64
#            os: ubuntu-latest
#            target: x86_64-unknown-linux-gnu
#
#          - build: linux-aarch64
#            os: ubuntu-latest
#            target: aarch64-unknown-linux-gnu
#
#          - build: win-x86
#            os: windows-latest
#            target: i686-pc-windows-msvc
#
#          - build: win-x86_64
#            os: windows-latest
#            target: x86_64-pc-windows-msvc
#
          - build: mac-x86_64
            os: macos-latest
            target: x86_64-apple-darwin

          - build: mac-aarch64
            os: macos-latest
            target: aarch64-apple-darwin


    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Get the release version from the tag
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ matrix.target }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
#          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }} --manifest-path rust/Cargo.toml

      - name: Create platform dir
        shell: bash
        run: |
          binary_name="opus_jni_rust"

          dirname="src/main/resources/natives/${{ matrix.build }}"
          mkdir "$dirname"
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            mv "rust/target/${{ matrix.target }}/release/$binary_name.dll" "$dirname"
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            mv "rust/target/${{ matrix.target }}/release/lib$binary_name.dylib" "$dirname"
          else
            mv "rust/target/${{ matrix.target }}/release/lib$binary_name.so" "$dirname"
          fi

          echo "ASSET=$dirname" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.build }}
          path: ${{ env.ASSET }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

  build:
    runs-on: ubuntu-latest
    needs: build-rust

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: src/main/resources/natives

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: opus-jni-rust.jar
          path: build/libs/opus-jni-rust.jar
